"""Added SliderImage model for image slider

Revision ID: 5101cb061ae6
Revises: 1b236e4ab020
Create Date: 2025-05-01 13:31:15.504412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5101cb061ae6'
down_revision = '1b236e4ab020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slider_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slider_image')
    # ### end Alembic commands ###
